[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]
name = "utils"

[dependencies]
anchor-lang = "1.1.2"
anchor-spl = {version = "1.1.2", features = ["metadata"]}
solana-program = "3.0.0"
mpl-token-metadata = { version = "=5.1.2-alpha.2" }
mpl-core = { version = "0.12.1" }